### ISSUE TITLE
How can i generate qt project

### ISSUE THREAD

**Issue by yunhai2009** [OlivierLDff/Qaterial#1]
How can i generate qt project?
Thank you vervy mach.

**Comment by OlivierLDff** [comment]
You should have a look here : https://github.com/OlivierLDff/QaterialGallery
Are you using qmake or cmake? I dont really know how to integrate with qmake but i guess just compile this library then use the resulting library to link to your project.
If using cmake have a look in QaterialGallery. What i do is I build Qaterial along with QaterialGallery.
I use cmake's FetchContent function to download Qaterial at generation Time:
```cmake

include(FetchContent)
FetchContent_Declare(
    Qaterial
    GIT_REPOSITORY "https://github.com/OlivierLDff/Qaterial"
    GIT_TAG "master"
)
FetchContent_MakeAvailable(Qaterial)

target_link_libraries(YourTarget Qaterial)

```

If you are doing like me, Qaterial is a static library, so qrc files needs to get loaded in your code


```cpp
#include <Qaterial.hpp>
int main(int argc, char *argv[])
{
    // It's important to set the high dip support before creating the gui app
    QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QGuiApplication app(argc, argv);
    QQmlApplicationEngine engine;

    Qaterial::Utils::loadResources();
    Qaterial::Utils::registerTypes();

    engine.load(QUrl("qrc:/Path/To/Your/Main.qml"));
    return app.exec();
}
```

And you simply need to add `import Qaterial 1.0` to use components in your files.
All examples are inside QaterialGallery.
