### ISSUE TITLE
Dialog Manager How to??

### ISSUE THREAD

**Issue by celibol** [OlivierLDff/Qaterial#113]
How to 2 line TextField with dialogManager??

For Ex: 

First Line NAME field
Second Line SURNAME field

How to read with DİalogManager??

**Comment by OlivierLDff** [comment]
You need to create your own dialog, put it in a component, and open it with `DialogManager.openFromComponent`.
If you have idea of a better API, I'm listening.
Have a nice day

**Comment by celibol** [comment]
function openFromComponent(comp)

Comp is ITEM or COMPONENT etc...

Its true?

**Comment by OlivierLDff** [comment]
`comp` is expected to be a `Component`

**Comment by celibol** [comment]
Component {
        id: _editComponent

        Qaterial.TextField{
            id: _fiyat

            width: parent.width
            Layout.fillWidth: true
            enabled: true
            title: "Fiyatı"
            placeholderText: "Ürün Fiyatını Girin"
            validator: DoubleValidator{notation: DoubleValidator.StandardNotation}
            leadingIconInline: true
            text: ""
            inputMethodHints: Qt.ImhSensitiveData
            trailingContent: Qaterial.TextFieldButtonContainer{
                Qaterial.TextFieldClearButton {}
            }
        } // Fiyat
    }

function editLine(){
        Qaterial.DialogManager.openFromComponent(_editComponent)
    }
    function menuClicked(ID){
        switch(ID){
            case  4: editLine(); break; // Edit        }
    }


.....

No any eror 

But dont work

**Comment by celibol** [comment]
WOWWWW

It's working
