### ISSUE TITLE
Qt project configuration

### ISSUE THREAD

**Issue by tolgayilmaz86** [OlivierLDff/Qaterial#125]
Is there any template project using pro files and qmake instead of cmake? Or how can I pull cmake configuration off from cmake and make on myself?

**Comment by OlivierLDff** [comment]
There is an install target if you want.
```bash
mkdir build && cd build
cmake ..
cmake --build . --target Qaterial --config Release -j
cmake --install . [--prefix <install-dir>]
```

Or [CGinMax/Qaterial](https://github.com/CGinMax/Qaterial/tree/Qt5.12.0) made a fork to integrate with qmake.

**Comment by tolgayilmaz86** [comment]
thanks will try.
