### ISSUE TITLE
ToolTip Simple sample not working on QaterialOnline

### ISSUE THREAD

**Issue by Daguerreo** [OlivierLDff/Qaterial#41]
Tooltips are not showing in ToolTip Simple sample on QaterialOnline. They are working properly in the positioned sample instead

**Comment by OlivierLDff** [comment]
It's because Qt Web assembly doesn't seem to support the hovered flag.
I updated the example to add `pressed` to display the tooltip. https://github.com/OlivierLDff/Qaterial/commit/9771391024fa9ce8c117785544e5c43dacef8430

It should be ok when QaterialOnline will redeploy

**Comment by Daguerreo** [comment]
I imaged was a wasm matter. Now works properly

**Comment by OlivierLDff** [comment]
Found the cause of the bug, seem that [Qt.styleHints.useHoverEffects](https://doc.qt.io/qt-5/qstylehints.html#useHoverEffects-prop) is false by default on wasm. I change this behavior in latest version of QaterialOnline to true by default.
All the hovered property of `AbstractButton` derived objects should work as expected.
