### ISSUE TITLE
QMake build file

### ISSUE THREAD

**Issue by ssakone** [OlivierLDff/Qaterial#55]
Can you add please qmake build file?

**Comment by OlivierLDff** [comment]
I don't know much about qmake, feel free to submit a PR. Supporting qmake that would to the same as my cmake script would be quite hard since i'm using cmake to download dependencies (QOlm, spdlog, MaterialDesignIcons, ...) and generating source files)
But i would advise you to move to cmake anyway since Qt is also moving to cmake. Have a look at https://github.com/OlivierLDff/QQuickStaticHelloWorld for a very simple qt quick project.
What problem do you encounter with cmake?
You should also check this great guide for modern cmake : https://cliutils.gitlab.io/modern-cmake/

**Comment by ssakone** [comment]
Yes i know,im verry new on cmake

**Comment by OlivierLDff** [comment]
So what is blocking you on cmake? Do you have a project you want to move to cmake and you can't?

**Comment by ssakone** [comment]
many things,
first Qt creator editor integration,
i use set(QML_IMP...
Not work,
Just one time its work, after restart project no,
I have build many other module and library, i integrate easly with include
.pri
Cmake doest not work with my mvcs2019 it show MSB1001 project file not
found, just mingw and arm

**Comment by ssakone** [comment]
i think you speak french, i can write you with this, because my english is
so bad

Le lun. 27 juil. 2020 à 07:03, Black Enokas <abdramanesakone1@gmail.com> a
écrit :

**Comment by OlivierLDff** [comment]
Arrives tu à builder Qaterial par example? Ou plus simple mon project [QQuickStaticHelloWorld](https://github.com/OlivierLDff/QQuickStaticHelloWorld)
![helloworldcmake](https://user-images.githubusercontent.com/17255804/88514270-103dbd80-cfea-11ea-8237-41282250dc03.gif)

**Comment by ssakone** [comment]
Oui sans problème,  avec mingw
J'ai meme créé un.autre project et integrer Qaterial

**Comment by ssakone** [comment]
Mais est il pas possibles de generer un lib comme libQaterial qui est seras
directement installé parmi les lib et fonctinneras automatiquement sans
pourtant avoir a integrer Qaterial a chaque project

Le lun. 27 juil. 2020 à 07:24, Black Enokas <abdramanesakone1@gmail.com> a
écrit :

**Comment by OlivierLDff** [comment]
![qaterialcompi4](https://user-images.githubusercontent.com/17255804/88516202-3153dd80-cfed-11ea-8283-921a842efef8.gif)

[Qaterial.zip](https://github.com/OlivierLDff/Qaterial/files/4980606/Qaterial.zip)

Ok i see what you mean, i haven't done any install target. But you can compile Qaterial as a library without any issue.
Note that in the screen `cmake ..` works and i don't need to do `cmake -DCMAKE_PREFIX_PATH=Path/to/qt` because i have an environment variable `Qt5_DIR` set to `C:\Qt\5.15.0\msvc2019_64`

**Comment by ssakone** [comment]
[image: image.png]
watch i copy file lib on msvc2019_64 lib directory but not work

**Comment by ssakone** [comment]
Have you telegram?

Le lun. 27 juil. 2020 à 09:57, Black Enokas <abdramanesakone1@gmail.com> a
écrit :

**Comment by OlivierLDff** [comment]
Je ne vois pas ton image

**Comment by ssakone** [comment]
[image: image.png]

**Comment by ssakone** [comment]
Its just, Application output error, module "Qaterial"" is not installed


Le lun. 27 juil. 2020 à 10:03, Black Enokas <abdramanesakone1@gmail.com> a
écrit :

**Comment by OlivierLDff** [comment]
As tu bien fait dans ton main.cpp

qaterial::loadQmlResources(); qaterial::registerQmlTypes();

**Comment by OlivierLDff** [comment]
Regarde le main.cpp du helloworld
https://olivierldff.github.io/Qaterial/Quickstart.html

Le lun. 27 juil. 2020 à 10:05, Olivier Le Doeuff <olivier.ldff@gmail.com> a
écrit :

**Comment by ssakone** [comment]
Now i have this error when i try compile
[image: image.png]

 link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS
"/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls'
version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*'
processorArchitecture='*'" /MANIFEST:embed /OUT:debug\untitled6.exe
@C:\Users\bot\AppData\Local\Temp\untitled6.exe.78072.5375.jom
main.obj : error LNK2019: symbole externe non r‚solu "void __cdecl
qaterial::registerQmlTypes(char const *,unsigned char,unsigned char)"
(?registerQmlTypes@qaterial@@YAXPEBDEE@Z) r‚f‚renc‚ dans la fonction main
main.obj : error LNK2019: symbole externe non r‚solu "void __cdecl
qaterial::loadQmlResources(void)" (?loadQmlResources@qaterial@@YAXXZ)
r‚f‚renc‚ dans la fonction main
debug\untitled6.exe : fatal error LNK1120: 2 externes non r‚solus
jom:
C:\Users\bot\Documents\build-untitled6-Desktop_Qt_5_15_0_MSVC2019_64bit-Debug\Makefile.Debug
[debug\untitled6.exe] Error 1120
jom:
C:\Users\bot\Documents\build-untitled6-Desktop_Qt_5_15_0_MSVC2019_64bit-Debug\Makefile
[debug] Error 2
10:38:28: Le processus "C:\Qt\Tools\Preview\Qt Creator
4.13.0-beta1\bin\jom.exe" s'est terminé avec le code 2.

**Comment by ssakone** [comment]
> Je ne vois pas ton image.
> J'ai discord si tu veux.

**Comment by ssakone** [comment]
i accidentrly close it

**Comment by OlivierLDff** [comment]
Il faut que tu ais les headers dans ton path d'include, et que tu te link à Qaterial.lib.
Mais je ne sais pas comment faire ça avec qmake. A quoi ressemble ton .pro?

**Comment by OlivierLDff** [comment]
Je pense qu'il faut quelque chose comme ça
```
LIBS += c:/Qaterial/build/Release/Qaterial.lib
INCLUDEPATH += c:/Qaterial/include`
LIBS += c:/Qaterial/build/_deps/spdlog-build/Release/spdlog.lib
LIBS += c:/Qaterial/build/_deps/qolm-build/Release/QOlm.lib
```

**Comment by ssakone** [comment]
j'ai deja mis les header, Pour integrer la lib il faut juste que je le
copie dans C:\Qt\5.15.0\msvc2019_64\lib,

Généralement c'est comme sa je fais

**Comment by OlivierLDff** [comment]
Peut être que ça marche, mais je te d'essayer `LIBS += c:/Qaterial/build/Release/Qaterial.lib`. Au moins tu devrais avoir un erreur de qmake s'il ne trouve pas la librairie je pense.

**Comment by ssakone** [comment]
sa requiert aussi spdlog.lib, que j'ai deja importé

Le lun. 27 juil. 2020 à 10:48, Black Enokas <abdramanesakone1@gmail.com> a
écrit :

**Comment by ssakone** [comment]
My project fille

`QT += quick

CONFIG += c++11
SOURCES += \
        main.cpp

RESOURCES += qml.qrc


LIBS += $$PWD/../../Downloads/Qaterial/Qaterial.lib \
    $$PWD/../../Downloads/Qaterial/spdlog.lib \
    $$PWD/../../Downloads/Qaterial/QOlm.lib
INCLUDEPATH += E:/homeMusic/Qaterial/include
DEPENDPATH += E:/homeMusic/Qaterial/include
`


`	link /NOLOGO /DYNAMICBASE /NXCOMPAT /OPT:REF /INCREMENTAL:NO /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:release\untitled6.exe @C:\Users\bot\AppData\Local\Temp\untitled6.exe.79108.500.jom
Qaterial.lib(Utils.obj) : error LNK2019: symbole externe non r‚solu "__declspec(dllimport) public: static void __cdecl QQuickStyle::setStyle(class QString const &)" (__imp_?setStyle@QQuickStyle@@SAXAEBVQString@@@Z) r‚f‚renc‚ dans la fonction "void __cdecl Qaterial_loadResources(void)" (?Qaterial_loadResources@@YAXXZ)
Qaterial.lib(Utils.obj) : error LNK2019: symbole externe non r‚solu "__declspec(dllimport) public: static void __cdecl QQuickStyle::setFallbackStyle(class QString const &)" (__imp_?setFallbackStyle@QQuickStyle@@SAXAEBVQString@@@Z) r‚f‚renc‚ dans la fonction "void __cdecl Qaterial_loadResources(void)" (?Qaterial_loadResources@@YAXXZ)
Qaterial.lib(Utils.obj) : error LNK2019: symbole externe non r‚solu __imp_SetProcessDPIAware r‚f‚renc‚ dans la fonction "void __cdecl `dynamic initializer for 'private: static class HighDpiFix HighDpiFix::singleton''(void)" (??__E?singleton@HighDpiFix@@0V1@A@@YAXXZ)
release\untitled6.exe : fatal error LNK1120: 3 externes non r‚solus`

**Comment by ssakone** [comment]
My main.cpp

`#include <QGuiApplication>
#include <Qaterial/Qaterial.hpp>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.addImportPath("qrc:///");
    qaterial::loadQmlResources();
    qaterial::registerQmlTypes();

    const QUrl url(QStringLiteral("qrc:/main.qml"));
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return QGuiApplication::exec();
}
`

**Comment by OlivierLDff** [comment]
I made it work
```
QT += quick quickcontrols2

CONFIG += c++11
SOURCES += HelloWorld.cpp

RESOURCES += HelloWorld.qrc

DEFINES += "QATERIAL_STATIC=1"

LIBS += C:/Users/olivi/Desktop/Qaterial/build/Release/Qaterial.lib
LIBS += C:/Users/olivi/Desktop/Qaterial/build/_deps/spdlog-build/Release/spdlog.lib
LIBS += C:/Users/olivi/Desktop/Qaterial/build/_deps/qolm-build/Release/QOlm.lib
LIBS += User32.lib
INCLUDEPATH += C:/Users/olivi/Desktop/Qaterial/include/
INCLUDEPATH += C:/Users/olivi/Desktop/Qaterial/build/_deps/spdlog-src/include
```

The problem was that QATERIAL_STATIC wasn't defined. Forgot about it since cmake define it automatically in super build.
Ensuite les QQuickStyle::setFallbackStyle c'est qu'il manque quickcontrols2 comme module
Et User32 c'est parce que j'appelle la focntion set process dpi aware de windows (pour géré les configs avec écran 4K et 1080p)

J'ai utilisé les sources de :
https://github.com/OlivierLDff/Qaterial/tree/master/tools/HelloWorld

**Comment by ssakone** [comment]
Yeah, its work,
Thank you.

please give me your discord.

**Comment by OlivierLDff** [comment]
Mon discord : reivilo1234#0459
