### ISSUE TITLE
Aggressive CMake error when using FetchContent for Qaterial

### ISSUE THREAD

**Issue by Milerius** [OlivierLDff/Qaterial#77]
Most of the time each time we refresh the CMake we have this line: `-- Download MaterialDesignIcons from https://github.com/OlivierLDff/MaterialDesignSvgo`

```
CMake Error at /Users/romanszterg/CLionProjects/atomicDEX-Pro/cmake-build-release-brew-clang-9/_deps/materialdesignicons-subbuild/materialdesignicons-populate-prefix/tmp/materialdesignicons-populate-gitupdate.cmake:133 (message):
  

  Failed to unstash changes in:
  '/Users/romanszterg/CLionProjects/atomicDEX-Pro/cmake-build-release-brew-clang-9/_deps/materialdesignicons-src/'.


  You will have to resolve the conflicts manually
```

This happens like 6/10 and this is very annoying, any suggestions to prevent the stash ? The folder is already downloaded once, why this is re evaluated each time ?

Usage:

```CMake
FetchContent_Declare(qmaterial URL https://github.com/OlivierLDff/Qaterial/archive/master.zip)
FetchContent_MakeAvailable(qmaterial)
```

**Comment by Milerius** [comment]
<img width="650" alt="Capture d’écran 2020-10-09 à 22 57 39" src="https://user-images.githubusercontent.com/21139416/95630836-d6297700-0a82-11eb-80f8-fdb17be593f4.png">
![Uploading Capture d’écran 2020-10-09 à 22.58.03.png…]()

**Comment by OlivierLDff** [comment]
Ok, i know why this happen, i have it sometimes too.
I will look how to resolve this.

This happen because it generate QaterialIcon.qrc inside the MaterialDesignIcon repository.
When you are doing a cmake a second time the file is stashed then poped. The issue seems to happen there.

**Comment by Milerius** [comment]
I think we can use zip bundle instead of using git in CMake fetch content @OlivierLDff it's what i did in my project for my Contents package and it's seems to work properly:

```
FetchContent_Declare(
        reproc
        URL https://github.com/DaanDeMeyer/reproc/archive/v13.0.1.zip
)
```

For example

**Comment by OlivierLDff** [comment]
Can you tell me if 1e7ed989b4045a93600d7569a694828817c0eaf3 fix your issue?

**Comment by Milerius** [comment]
> Can you tell me if [1e7ed98](https://github.com/OlivierLDff/Qaterial/commit/1e7ed989b4045a93600d7569a694828817c0eaf3) fix your issue?
> At least now it is cleaner.
> 
> I tested with this _CMakeLists.txt_ on windows 10 & linux. But i wasn't able to reproduce your error in both os.
> 
> ```
> cmake_minimum_required(VERSION 3.14 FATAL_ERROR)
> 
> project("qmaterial fetch bug")
> include(FetchContent)
> FetchContent_Declare(qmaterial URL https://github.com/OlivierLDff/Qaterial/archive/master.zip)
> FetchContent_MakeAvailable(qmaterial)
> ```

Yeah obviously the CMake that you show here will work because this is using the `.zip` approach, there is no such a git stash in this case, because there is no git at all.

That's was my proposed solution.

**Comment by OlivierLDff** [comment]
Can you give me minimum reproductible example?

**Comment by Milerius** [comment]
Still have the same problem @OlivierLDff with the example above

**Comment by OlivierLDff** [comment]
What is your operating system?
What is your git config? Can you replicate inside a docker?
Can you show the git status of materialdesignicons repo?

**Comment by Milerius** [comment]
> What is your operating system?
> What is your git config? Can you replicate inside a docker?
> Can you show the git status of materialdesignicons repo?

?

**Comment by Milerius** [comment]
Nono, i just forget to empty the CMakeCache after updating !

**Comment by OlivierLDff** [comment]
I replied after seeing your first post saying it was still not working

**Comment by Milerius** [comment]
Thanks you for your time ! Keep the good job !
