### ISSUE TITLE
How can i install to qt's directory qml

### ISSUE THREAD

**Issue by gersure** [OlivierLDff/Qaterial#94]
i want to use in qtcreator, but now can't make it

**Comment by OlivierLDff** [comment]
I think it is the same as https://github.com/OlivierLDff/Qaterial/issues/78
I don't have time to support that for now, but feel free to pull request.
Qaterial should be compiled as a plug-in for that.

**Comment by ssakone** [comment]
You have to create qt project as cmake in QtCreator first after add this line on your cmakefile after find_package line
 `include(FetchContent)
FetchContent_Declare(
  Qaterial
  GIT_REPOSITORY https://github.com/OlivierLDff/Qaterial.git
  GIT_TAG        master
  GIT_SHALLOW    1
)
FetchContent_MakeAvailable(Qaterial)
`
`target_link_libraries(... Qaterial) 
`
dont forgot to add Qaterial in target_link_libraries,

after follow for the next step instruction here https://olivierldff.github.io/Qaterial/Quickstart.html,
if you want to add Qaterial completion and syntax recongnition in QtCreator
copy in Qaterial repos qml/Qaterial ---> folder in your qt installation directory like (Qt__path)/version/compiler(msvc2019)/qml
